name: veritas

channels:
  - defaults  # Always leave this channel
  - conda-forge

dependencies:
  - python=3.8.6
  - scipy=1.5.2
  - numpy=1.19.2
  - matplotlib=3.3.2
  - pandas=1.1.3
  - scikit-learn=0.23.2
  - imbalanced-learn=0.7.0
  - jupyterlab=2.2.6
  - pytest=6.1.1
  - flake8=3.8.4
  - pip=20.2.4
  # - pip:  # Add packages not available for conda here
  #     - plotly
